# Example YAML configuration for testing
name: Example Project
version: 1.0.0
description: This is a test YAML file.
database:
  host: localhost
  port: 5432
  user: admin
  password: secret
features:
  - authentication
  - logging
  - notifications
enabled: true
metadata:
  created_by: ayush-jadaun
  date: 2025-06-05