version: "3.8"

services:
  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    container_name: chroma
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma/chroma
    restart: unless-stopped

  chroma-service:
    build:
      context: ./utils
      dockerfile: Dockerfile
    container_name: chroma-service
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "8001:8001"
    volumes:
      - chroma_data:/chroma/chroma
    depends_on:
      - chroma

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    entrypoint: ["/bin/sh", "-c", "ollama pull llama3 || true; ollama serve"]

  daios-agent:
    build: .
    container_name: daios-agent
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - COHERE_API_KEY=${COHERE_API_KEY}
      - CHROMA_BRIDGE_URL=http://chroma-service:8001
      - SERPER_API_KEY=${SERPER_API_KEY}
      - OLLAMA_URL=http://ollama:11434
    depends_on:
      - chroma-service
      - ollama
    volumes:
      - /e/daios/sandbox:/app/sandbox  # <-- This is your bind mount

volumes:
  chroma_data:
  ollama_data: