version: "3.8"

services:
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    container_name: chroma
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma/chroma
    restart: unless-stopped

  chroma-service:
    build:
      context: ./utils
      dockerfile: Dockerfile
    container_name: chroma-service
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "8001:8001"
    volumes:
      - chroma_data:/chroma/chroma
    depends_on:
      - chroma

  task-planner:
    build:
      context: ./taskPlanner
      dockerfile: Dockerfile
    container_name: task-planner
    environment:
      - PYTHONUNBUFFERED=1
      - OLLAMA_URL=http://ollama:11434
    ports:
      - "8002:8002"
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    entrypoint: ["/bin/sh", "-c", "ollama pull llama3 || true; ollama serve"]

  api-server:
    build: .
    container_name: daios-api-server
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - COHERE_API_KEY=${COHERE_API_KEY}
      - CHROMA_BRIDGE_URL=http://chroma-service:8001
      - SERPER_API_KEY=${SERPER_API_KEY}
      - OLLAMA_URL=http://ollama:11434
      - TASK_PLANNER_URL=http://task-planner:8002
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
      - chroma-service
      - task-planner
      - ollama
    volumes:
      - /e/daios/sandbox:/app/sandbox
    command: ["node", "index.js"]

  debug-agent:
    build: .
    container_name: daios-debug-agent
    environment:
      - CHROMA_BRIDGE_URL=http://chroma-service:8001
      - OLLAMA_URL=http://ollama:11434
      - TASK_PLANNER_URL=http://task-planner:8002
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
      - chroma-service
      - task-planner
      - ollama
    command: ["node", "agentsEntry/debugAgentEntry.js"]

  dev-agent:
    build: .
    container_name: daios-dev-agent
    environment:
      - CHROMA_BRIDGE_URL=http://chroma-service:8001
      - OLLAMA_URL=http://ollama:11434
      - TASK_PLANNER_URL=http://task-planner:8002
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
      - chroma-service
      - task-planner
      - ollama
    command: ["node", "agentsEntry/devAgentEntry.js"]

  ops-agent:
    build: .
    container_name: daios-ops-agent
    environment:
      - CHROMA_BRIDGE_URL=http://chroma-service:8001
      - OLLAMA_URL=http://ollama:11434
      - TASK_PLANNER_URL=http://task-planner:8002
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
      - chroma-service
      - task-planner
      - ollama
    command: ["node", "agentsEntry/opsAgentEntry.js"]

volumes:
  chroma_data:
  ollama_data: